apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ud97bsrti-go
  janus-idp.io/tekton: ud97bsrti-go
  backstage.io/kubernetes-id: ud97bsrti-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: ud97bsrti-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
