apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ud97bsrti-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ud97bsrti-go 
  name: ud97bsrti-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ud97bsrti-go 
